export default {
  '-- intro': { type: 'separator', title: 'Introduction' },
  'getting-started': 'Getting Started',
  'migrating-to-2': 'Migrating to 2.0',
  upgrading: 'Upgrading to 2.6.0',
  compatibility: 'Compatibility & Maintenance',
  cdn: 'Use from a CDN',
  'core-concepts': 'Core Concepts',
  architecture: 'Architecture',
  widget: 'The Widget Tier',
  'terminal-workspace': 'Optional Terminal Workspace',
  frameworks: 'Framework Integration',
  // The old Vue guide's URL, kept only to send readers to the Vue 3 section.
  vue: { display: 'hidden' },

  '-- guides': { type: 'separator', title: 'Guides' },
  'chart-types': 'Chart Types',
  'series-and-styling': 'Series & Styling',
  rendering: 'Render Backends & SVG Export',
  'timeframes-and-tick-charts': 'Timeframes & Tick Charts',
  timezones: 'Timezones',
  'scales-and-panes': 'Scales & Panes',
  'price-levels': 'Price Levels & Axis Chrome',
  'symbol-comparison': 'Symbol Comparison',
  'chart-linking': 'Chart Linking',
  'chart-grid': 'Chart Grid',
  themes: 'Theming & Chart Options',
  'branding-and-watermarks': 'Branding & Watermarks',
  'settings-and-menus': 'Settings & Menus',
  objects: 'Objects',
  indicators: 'Indicators',
  'open-interest': 'Open Interest',
  alerts: 'Trader Alerts',
  transforms: 'Transforms',
  'primitives-and-plugins': 'Primitives & Plugins',
  'drawing-tools': 'Drawing Tools',
  'drawing-clipboard': 'Drawing Clipboard',
  'profiles-and-orderflow': 'Profiles & Order Flow',
  'market-profile': 'Market Profile (TPO)',
  'market-profile-examples': 'Profile Demo & Themes',
  'volume-profile': 'Volume Profile',
  'market-replay': 'Market Replay',
  'crosshair-and-legend': 'Crosshair & Legend',
  state: 'Chart State',
  workspaces: 'Workspaces & Templates',
  'watchlists-and-news': 'Watchlists & News',
  'chart-data-export': 'Chart Data & CSV Export',
  interactions: 'Interactions & A11y',
  'keyboard-shortcuts': 'Keyboard Shortcuts',
  'undo-history': 'Undo and Redo',
  events: 'Events',
  mobile: 'Mobile & Touch',

  '-- trading': { type: 'separator', title: 'Trading' },
  'trading-api': 'Trading API',
  trading: 'Order Engine & Ladder',
  'trading-accounts': 'Accounts & Advanced Orders',
  'depth-of-market': 'Depth of Market Demo',

  '-- data': { type: 'separator', title: 'Data & Feeds' },
  instruments: 'Instrument Metadata',
  'data-loading': 'Data Loading',
  'live-data': 'Live Data (OpenAlgo)',
  'openalgo-compatibility': 'OpenAlgo Compatibility',
  'performance-and-operations': 'Performance & Operations',
  'data-feeds': 'Custom Data Feeds',
  'bar-cache': 'Bar Cache',
  'data-variants': 'Data Variants',
  'custom-intervals': 'Custom Intervals',

  '-- reference': { type: 'separator', title: 'Reference' },
  types: 'Types Reference',
  constants: 'Constants & Helpers',
  glossary: 'Glossary',
  'release-notes': 'Release Notes',
};
